name: Release_Stable

on:
  push:
    tags:
      - "**"

jobs:
  build_artifact:
    name: Build and upload artifact
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Build with dotnet
        run: |
          dotnet build --configuration Release --source https://api.nuget.org/v3/index.json src/Dtmcli/Dtmcli.csproj         
          dotnet build --configuration Release --source https://api.nuget.org/v3/index.json src/Dtmgrpc/Dtmgrpc.csproj                
          dotnet build --configuration Release --source https://api.nuget.org/v3/index.json src/DtmCommon/DtmCommon.csproj
          dotnet build --configuration Release --source https://api.nuget.org/v3/index.json src/DtmSERedisBarrier/DtmSERedisBarrier.csproj
          dotnet build --configuration Release --source https://api.nuget.org/v3/index.json src/DtmMongoBarrier/DtmMongoBarrier.csproj
          dotnet build --configuration Release --source https://api.nuget.org/v3/index.json src/DtmDapr/DtmDapr.csproj
          dotnet build --configuration Release --source https://api.nuget.org/v3/index.json src/Dtmworkflow/Dtmworkflow.csproj
      - name: Pack with dotnet
        run: |
          dotnet pack src/Dtmcli/Dtmcli.csproj -o /home/runner/work/nugetpkgs -c Release --no-build
          dotnet pack src/Dtmgrpc/Dtmgrpc.csproj -o /home/runner/work/nugetpkgs -c Release --no-build
          dotnet pack src/DtmCommon/DtmCommon.csproj -o /home/runner/work/nugetpkgs -c Release --no-build
          dotnet pack src/DtmSERedisBarrier/DtmSERedisBarrier.csproj -o /home/runner/work/nugetpkgs -c Release --no-build
          dotnet pack src/DtmMongoBarrier/DtmMongoBarrier.csproj -o /home/runner/work/nugetpkgs -c Release --no-build
          dotnet pack src/DtmDapr/DtmDapr.csproj -o /home/runner/work/nugetpkgs -c Release --no-build
          dotnet pack src/Dtmworkflow/Dtmworkflow.csproj -o /home/runner/work/nugetpkgs -c Release --no-build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: nugetpkgs
          path: /home/runner/work/nugetpkgs

  release_nuget:
    name: Release to Nuget
    needs: build_artifact
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: nugetpkgs
      - name: list nugetpkgs
        run: ls nugetpkgs
      - name: Release
        run: |
          for file in nugetpkgs/*.nupkg
          do
            dotnet nuget push $file -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate -s https://www.nuget.org/api/v2/package
          done
